// <auto-generated />
using System;
using Illig_AI_Platform.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Illig_AI_Platform.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260716095335_AddAngebotVertriebsbedingungen")]
    partial class AddAngebotVertriebsbedingungen
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Illig_AI_Platform.Shared.Auftragsanlage.Angebot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Angebotsnummer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BlobPfad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dateiname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("HochgeladenAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Incoterm")
                        .HasColumnType("longtext");

                    b.Property<string>("IncotermOrt")
                        .HasColumnType("longtext");

                    b.Property<string>("Kundenadresse")
                        .HasColumnType("longtext");

                    b.Property<string>("Kundenname")
                        .HasColumnType("longtext");

                    b.Property<string>("Versandbedingung")
                        .HasColumnType("longtext");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("Volltext")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Zahlungsbedingungen")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Angebotsnummer", "Version")
                        .IsUnique();

                    b.ToTable("Angebote");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Auftragsanlage.AngebotPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AngebotId")
                        .HasColumnType("int");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Einzelpreis")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Gesamtbetrag")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Menge")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("AngebotId");

                    b.ToTable("AngebotPositionen");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Auftragsanlage.Auftragsbestaetigung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AngebotId")
                        .HasColumnType("int");

                    b.Property<string>("BlobPfad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dateiname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("HochgeladenAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Kundenadresse")
                        .HasColumnType("longtext");

                    b.Property<string>("Kundenname")
                        .HasColumnType("longtext");

                    b.Property<string>("LieferterminAngebot")
                        .HasColumnType("longtext");

                    b.Property<string>("LieferterminBestaetigung")
                        .HasColumnType("longtext");

                    b.Property<bool>("LieferterminIdentisch")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nummer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SonstigeAbweichungen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Volltext")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Zahlungsbedingungen")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AngebotId");

                    b.ToTable("Auftragsbestaetigungen");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Auftragsanlage.AuftragsbestaetigungPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuftragsbestaetigungId")
                        .HasColumnType("int");

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Einzelpreis")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Gesamtbetrag")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Menge")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.HasKey("Id");

                    b.HasIndex("AuftragsbestaetigungId");

                    b.ToTable("AuftragsbestaetigungPositionen");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.MaschinentypStueckliste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ImportiertAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Kopfmaterial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaschinentypSchluessel")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("MaschinentypSchluessel")
                        .IsUnique();

                    b.ToTable("MaschinentypStuecklisten");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.MaximalstuecklistenPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artikelnummer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Bedingung")
                        .HasColumnType("longtext");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Einheit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaschinentypStuecklisteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Menge")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MaschinentypStuecklisteId");

                    b.HasIndex("ParentId");

                    b.ToTable("MaximalstuecklistenPositionen");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Data.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PlausibilityCheck"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SearchSystem"
                        },
                        new
                        {
                            Id = 4,
                            Name = "OrderCreationSales"
                        },
                        new
                        {
                            Id = 5,
                            Name = "OrderCreationBackoffice"
                        });
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Data.SapStagingEintrag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("EmpfangenAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UseCase")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("UseCase", "EmpfangenAm");

                    b.ToTable("SapStagingEintraege");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.StuecklistenPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artikelnummer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Auftragsnummer")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Einheit")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("ImportiertAm")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Menge")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Auftragsnummer");

                    b.ToTable("StuecklistenPositionen");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.StuecklistenpruefungVerlaufEintrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Auftragsnummer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BlobPfad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dateiname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("Datum")
                        .HasColumnType("date");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Kundennummer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Maschinentyp")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId");

                    b.ToTable("StuecklistenpruefungVerlaufEintraege");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Data.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("PreferredLanguage")
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileImageBase64")
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileImageType")
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .HasColumnType("longtext");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Data.UserProfileRole", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("char(36)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserProfileId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserProfileRoles");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.VerlaufMerkmal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Kategorie")
                        .HasColumnType("int");

                    b.Property<string>("Merkmalsnummer")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VerlaufEintragId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VerlaufEintragId");

                    b.HasIndex("Kategorie", "Merkmalsnummer");

                    b.ToTable("VerlaufMerkmale");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Auftragsanlage.AngebotPosition", b =>
                {
                    b.HasOne("Illig_AI_Platform.Shared.Auftragsanlage.Angebot", null)
                        .WithMany()
                        .HasForeignKey("AngebotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Auftragsanlage.Auftragsbestaetigung", b =>
                {
                    b.HasOne("Illig_AI_Platform.Shared.Auftragsanlage.Angebot", null)
                        .WithMany()
                        .HasForeignKey("AngebotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Auftragsanlage.AuftragsbestaetigungPosition", b =>
                {
                    b.HasOne("Illig_AI_Platform.Shared.Auftragsanlage.Auftragsbestaetigung", null)
                        .WithMany()
                        .HasForeignKey("AuftragsbestaetigungId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.MaximalstuecklistenPosition", b =>
                {
                    b.HasOne("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.MaschinentypStueckliste", null)
                        .WithMany()
                        .HasForeignKey("MaschinentypStuecklisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Data.UserProfileRole", b =>
                {
                    b.HasOne("Illig_AI_Platform.Shared.Data.Role", "Role")
                        .WithMany("UserProfileRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Illig_AI_Platform.Shared.Data.UserProfile", "UserProfile")
                        .WithMany("UserProfileRoles")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.VerlaufMerkmal", b =>
                {
                    b.HasOne("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.StuecklistenpruefungVerlaufEintrag", null)
                        .WithMany()
                        .HasForeignKey("VerlaufEintragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Data.Role", b =>
                {
                    b.Navigation("UserProfileRoles");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Data.UserProfile", b =>
                {
                    b.Navigation("UserProfileRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
