// <auto-generated />
using System;
using Illig_AI_Platform.Shared.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Illig_AI_Platform.Shared.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Illig_AI_Platform.Shared.Auftragsanlage.Angebot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Angebotsnummer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BlobPfad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dateiname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Freigegeben")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("FreigegebenAm")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("FreigegebenVonUserProfileId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("GueltigBis")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("GueltigkeitsdatumKommentar")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("HochgeladenAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Incoterm")
                        .HasColumnType("longtext");

                    b.Property<string>("IncotermKommentar")
                        .HasColumnType("longtext");

                    b.Property<string>("IncotermOrt")
                        .HasColumnType("longtext");

                    b.Property<int?>("KundeId")
                        .HasColumnType("int");

                    b.Property<string>("KundeKommentar")
                        .HasColumnType("longtext");

                    b.Property<string>("Kundenadresse")
                        .HasColumnType("longtext");

                    b.Property<string>("Kundenname")
                        .HasColumnType("longtext");

                    b.Property<string>("Lieferadresse")
                        .HasColumnType("longtext");

                    b.Property<string>("LieferadresseKommentar")
                        .HasColumnType("longtext");

                    b.Property<string>("Liefertermin")
                        .HasColumnType("longtext");

                    b.Property<string>("LieferterminKommentar")
                        .HasColumnType("longtext");

                    b.Property<bool?>("SapFuehrendBestaetigt")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SapFuehrendKommentar")
                        .HasColumnType("longtext");

                    b.Property<bool?>("SapSparteBestaetigt")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SapSparteKommentar")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Verkaeufer")
                        .HasColumnType("longtext");

                    b.Property<string>("VerkaeuferKommentar")
                        .HasColumnType("longtext");

                    b.Property<string>("Versandbedingung")
                        .HasColumnType("longtext");

                    b.Property<string>("VersandbedingungKommentar")
                        .HasColumnType("longtext");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.Property<string>("VersionsKommentar")
                        .HasColumnType("longtext");

                    b.Property<string>("Volltext")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ZahlungsbedingungCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Zahlungsbedingungen")
                        .HasColumnType("longtext");

                    b.Property<string>("ZahlungsbedingungenKommentar")
                        .HasColumnType("longtext");

                    b.Property<string>("Zahlungsplan")
                        .HasColumnType("longtext");

                    b.Property<string>("ZahlungsplanKommentar")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("FreigegebenVonUserProfileId");

                    b.HasIndex("KundeId");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("Angebotsnummer", "Version")
                        .IsUnique();

                    b.ToTable("Angebote");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Auftragsanlage.Auftragsbestaetigung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AngebotId")
                        .HasColumnType("int");

                    b.Property<string>("BlobPfad")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dateiname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("HochgeladenAm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("KundeId")
                        .HasColumnType("int");

                    b.Property<string>("Kundenadresse")
                        .HasColumnType("longtext");

                    b.Property<string>("Kundenname")
                        .HasColumnType("longtext");

                    b.Property<string>("LieferterminAngebot")
                        .HasColumnType("longtext");

                    b.Property<string>("LieferterminBestaetigung")
                        .HasColumnType("longtext");

                    b.Property<bool>("LieferterminIdentisch")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Nummer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("SonstigeAbweichungen")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Volltext")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Zahlungsbedingungen")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AngebotId");

                    b.HasIndex("KundeId");

                    b.HasIndex("UserProfileId");

                    b.ToTable("Auftragsbestaetigungen");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Auftragsinformationen.SharePointSynchronisationsstand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeltaLink")
                        .HasColumnType("longtext");

                    b.Property<string>("DriveId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LetzterErfolgAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LetzterFehler")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LetzterVersuchAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("OrdnerItemId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Quelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Quelle")
                        .IsUnique();

                    b.ToTable("SharePointSynchronisationsstaende");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Data.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PlausibilityCheck"
                        },
                        new
                        {
                            Id = 3,
                            Name = "SearchSystem"
                        },
                        new
                        {
                            Id = 4,
                            Name = "OrderCreationSales"
                        },
                        new
                        {
                            Id = 5,
                            Name = "OrderCreationBackoffice"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Lieferantenassistent"
                        },
                        new
                        {
                            Id = 7,
                            Name = "DEV"
                        });
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Data.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ObjectId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PostalCode")
                        .HasColumnType("longtext");

                    b.Property<string>("PreferredLanguage")
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileImageBase64")
                        .HasColumnType("longtext");

                    b.Property<string>("ProfileImageType")
                        .HasColumnType("longtext");

                    b.Property<string>("Street")
                        .HasColumnType("longtext");

                    b.Property<string>("Vorname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ObjectId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Data.UserProfileRole", b =>
                {
                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("char(36)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserProfileId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserProfileRoles");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Kunden.Kunde", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<DateTime>("AktualisiertAm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Kundennummer")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("NormalisierteAdresse")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NormalisierterName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Kundennummer")
                        .IsUnique();

                    b.HasIndex("NormalisierterName", "NormalisierteAdresse");

                    b.ToTable("Kunden");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Kunden.KundenPartneradresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Hauptkundennummer")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ImportiertAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Land")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ort")
                        .HasColumnType("longtext");

                    b.Property<string>("PartnerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Partnerrolle")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Plz")
                        .HasColumnType("longtext");

                    b.Property<string>("Strasse")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Hauptkundennummer", "Partnerrolle")
                        .IsUnique();

                    b.ToTable("KundenPartneradressen");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Kunden.KundenQuelle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ErfasstAm")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("KundeId")
                        .HasColumnType("int");

                    b.Property<string>("Kundenadresse")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Kundenname")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Kundennummer")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("QuellId")
                        .HasColumnType("int");

                    b.Property<int>("Quelltyp")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KundeId");

                    b.HasIndex("Quelltyp", "QuellId")
                        .IsUnique();

                    b.ToTable("KundenQuellen");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Lieferantenassistent.Dispositionsposition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Auftragsbestaetigung")
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("Belegdatum")
                        .HasColumnType("date");

                    b.Property<decimal>("Bestellmenge")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Bestellmengeneinheit")
                        .HasColumnType("longtext");

                    b.Property<string>("EinkaeuferEmail")
                        .HasColumnType("longtext");

                    b.Property<string>("Einkaeufergruppe")
                        .HasColumnType("longtext");

                    b.Property<string>("EinkaeufergruppenName")
                        .HasColumnType("longtext");

                    b.Property<string>("Einkaufsbeleg")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Einteilungsmenge")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Einteilungsnummer")
                        .HasColumnType("longtext");

                    b.Property<decimal>("GelieferteMenge")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("ImportiertAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Kurztext")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LabNr")
                        .HasColumnType("longtext");

                    b.Property<int>("LieferantKreditor")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Lieferdatum")
                        .HasColumnType("date");

                    b.Property<string>("Material")
                        .HasColumnType("longtext");

                    b.Property<string>("MaterialgruppenCode")
                        .HasColumnType("longtext");

                    b.Property<string>("MaterialgruppenName")
                        .HasColumnType("longtext");

                    b.Property<decimal>("MengeInLagerME")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("Nettopreis")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("NochZuLiefernMenge")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Preiseinheit")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Schluessel")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VerantwortlichePerson")
                        .HasColumnType("longtext");

                    b.Property<string>("Waehrung")
                        .HasColumnType("longtext");

                    b.Property<string>("Werk")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LieferantKreditor");

                    b.HasIndex("Schluessel");

                    b.ToTable("Dispositionspositionen");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Lieferantenassistent.Lieferant", b =>
                {
                    b.Property<int>("Kreditor")
                        .HasColumnType("int");

                    b.Property<int?>("AdressNummer")
                        .HasColumnType("int");

                    b.Property<string>("Land")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Ort")
                        .HasColumnType("longtext");

                    b.Property<int?>("Postleitzahl")
                        .HasColumnType("int");

                    b.Property<string>("Strasse")
                        .HasColumnType("longtext");

                    b.HasKey("Kreditor");

                    b.ToTable("Lieferanten");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Lieferantenassistent.LieferantEmailAdresse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdressNummer")
                        .HasColumnType("int");

                    b.Property<string>("EmailAdresse")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IstStandard")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KontaktTyp")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AdressNummer");

                    b.ToTable("LieferantEmailAdressen");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.MaschinentypStueckliste", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BomTyp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateOnly>("GueltigAm")
                        .HasColumnType("date");

                    b.Property<DateTime>("ImportiertAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Kopfmaterial")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("MaschinentypSchluessel")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Stuecklistenalternative")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Stuecklistenverwendung")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Werk")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaschinentypSchluessel")
                        .IsUnique();

                    b.ToTable("MaschinentypStuecklisten");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.MaximalstuecklistenPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artikelnummer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Bedingung")
                        .HasColumnType("longtext");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Dokumentnummer")
                        .HasColumnType("longtext");

                    b.Property<string>("Dokumenttyp")
                        .HasColumnType("longtext");

                    b.Property<string>("Dokumentversion")
                        .HasColumnType("longtext");

                    b.Property<string>("Einheit")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal?>("Gesamtmenge")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("MaschinentypStuecklisteId")
                        .HasColumnType("int");

                    b.Property<decimal>("Menge")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.Property<int>("Reihenfolge")
                        .HasColumnType("int");

                    b.Property<string>("SapNodeId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SapPosition")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("MaschinentypStuecklisteId");

                    b.HasIndex("ParentId");

                    b.HasIndex("MaschinentypStuecklisteId", "SapNodeId")
                        .IsUnique();

                    b.ToTable("MaximalstuecklistenPositionen");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.StuecklistenPosition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Artikelnummer")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Auftragsnummer")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Auftragsposition")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("BomTyp")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Einheit")
                        .HasColumnType("longtext");

                    b.Property<DateOnly>("GueltigAm")
                        .HasColumnType("date");

                    b.Property<DateTime>("ImportiertAm")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("Menge")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("NodeId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ParentNodeId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Position")
                        .HasColumnType("int");

                    b.Property<string>("RootNodeId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SapPosition")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("NodeId");

                    b.HasIndex("Auftragsnummer", "Auftragsposition");

                    b.ToTable("StuecklistenPositionen");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.StuecklistenpruefungVerlaufEintrag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AnalyseFehler")
                        .HasColumnType("longtext");

                    b.Property<int?>("AnalyseStatus")
                        .HasColumnType("int");

                    b.Property<string>("Auftragsnummer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("BlobPfad")
                        .HasColumnType("longtext");

                    b.Property<string>("Dateiname")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateOnly?>("Datum")
                        .HasColumnType("date");

                    b.Property<string>("ETag")
                        .HasMaxLength(512)
                        .HasColumnType("varchar(512)");

                    b.Property<int>("ErreichterSchritt")
                        .HasColumnType("int");

                    b.Property<DateTime>("ErstelltAm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("GeloeschtAm")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("KundeId")
                        .HasColumnType("int");

                    b.Property<string>("Kundenadresse")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Kundenname")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Kundennummer")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Maschinentyp")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Quelle")
                        .HasColumnType("int");

                    b.Property<string>("SapDateiname")
                        .HasColumnType("longtext");

                    b.Property<string>("SharePointDriveId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("SharePointErstelltAm")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SharePointGeaendertAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SharePointItemId")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("StuecklisteJson")
                        .HasColumnType("longtext");

                    b.Property<Guid?>("UserProfileId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("VerarbeitetAm")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("VergleichsErgebnisJson")
                        .HasColumnType("longtext");

                    b.Property<string>("WebUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("varchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("Auftragsnummer");

                    b.HasIndex("KundeId");

                    b.HasIndex("Kundennummer");

                    b.HasIndex("Quelle");

                    b.HasIndex("UserProfileId");

                    b.HasIndex("AnalyseStatus", "GeloeschtAm");

                    b.HasIndex("SharePointDriveId", "SharePointItemId")
                        .IsUnique();

                    b.ToTable("StuecklistenpruefungVerlaufEintraege");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.VerlaufMerkmal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschreibung")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("Kategorie")
                        .HasColumnType("int");

                    b.Property<string>("Merkmalsnummer")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("VerlaufEintragId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VerlaufEintragId");

                    b.HasIndex("Kategorie", "Merkmalsnummer");

                    b.ToTable("VerlaufMerkmale");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Auftragsanlage.Angebot", b =>
                {
                    b.HasOne("Illig_AI_Platform.Shared.Kunden.Kunde", null)
                        .WithMany()
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Auftragsanlage.Auftragsbestaetigung", b =>
                {
                    b.HasOne("Illig_AI_Platform.Shared.Auftragsanlage.Angebot", null)
                        .WithMany()
                        .HasForeignKey("AngebotId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Illig_AI_Platform.Shared.Kunden.Kunde", null)
                        .WithMany()
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Data.UserProfileRole", b =>
                {
                    b.HasOne("Illig_AI_Platform.Shared.Data.Role", "Role")
                        .WithMany("UserProfileRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Illig_AI_Platform.Shared.Data.UserProfile", "UserProfile")
                        .WithMany("UserProfileRoles")
                        .HasForeignKey("UserProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("UserProfile");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Kunden.KundenQuelle", b =>
                {
                    b.HasOne("Illig_AI_Platform.Shared.Kunden.Kunde", null)
                        .WithMany()
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.MaximalstuecklistenPosition", b =>
                {
                    b.HasOne("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.MaschinentypStueckliste", null)
                        .WithMany()
                        .HasForeignKey("MaschinentypStuecklisteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.StuecklistenpruefungVerlaufEintrag", b =>
                {
                    b.HasOne("Illig_AI_Platform.Shared.Kunden.Kunde", null)
                        .WithMany()
                        .HasForeignKey("KundeId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.VerlaufMerkmal", b =>
                {
                    b.HasOne("Illig_AI_Platform.Shared.Plausibilitaetspruefung.Stuecklistenpruefung.StuecklistenpruefungVerlaufEintrag", null)
                        .WithMany()
                        .HasForeignKey("VerlaufEintragId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Data.Role", b =>
                {
                    b.Navigation("UserProfileRoles");
                });

            modelBuilder.Entity("Illig_AI_Platform.Shared.Data.UserProfile", b =>
                {
                    b.Navigation("UserProfileRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
